#!/usr/bin/python3
"""Hermes SRC quality gate.

Reads a probe_results.tsv generated by Hermes SRC workflows and emits a
conservative submit/no-submit decision. This is a heuristic gate; Hermes main
agent still performs the final reasoning and report writing.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Dict, List

SENSITIVE_PATTERNS = [
    ("pii", re.compile(r"姓名|手机号|身份证|学号|工号|邮箱|email|mobile|phone|idcard|identity", re.I)),
    ("auth", re.compile(r"token|authorization|session|jwt|ticket|secret|appsecret|apikey|access[_-]?key", re.I)),
    ("business", re.compile(r"订单|支付|金额|余额|成绩|课程|申请|流程|审批|借阅|住址|部门|组织|appName|serviceName", re.I)),
    ("sql_error", re.compile(r"SQLSyntaxErrorException|SQLException|mysql|oracle|postgres|mapper\.java|Unknown database|syntax error", re.I)),
    ("upload", re.compile(r"fileUrl|resId|ossId|genName|downloadUrl|upload.*success|上传成功", re.I)),
    ("rce", re.compile(r"uid=|gid=|root:|/bin/bash|Windows IP Configuration", re.I)),
    ("cors", re.compile(r"access-control-allow-origin|access-control-allow-credentials", re.I)),
]

NEGATIVE_PATTERNS = re.compile(
    r"Token失效|token信息不存在|FA_INVALID_SESSION|未登录|请登录|login|Login|登录|404 Not Found|403 Forbidden|Error Page|unexpected user service|empty|^$",
    re.I,
)

STRONG_HITS = {"pii", "auth", "sql_error", "upload", "rce"}
FALSE_POSITIVE_DECISIONS = {"REJECT_FALSE_POSITIVE"}
NEGATIVE_DECISIONS = {"NEGATIVE_OR_LOW_SIGNAL", "DO_NOT_SUBMIT"}
FALSE_POSITIVE_CLASSES = {
    "EMPTY_OR_UNREACHABLE",
    "WAF_BLOCK",
    "LOGIN_OR_AUTH_REQUIRED",
    "UNIFIED_ERROR",
    "EXACT_CONTROL_MATCH",
    "SPA_FALLBACK",
}


def read_rows(path: Path) -> List[Dict[str, str]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    first = text.splitlines()[0] if text.splitlines() else ""
    if "\t" in first:
        reader = csv.DictReader(text.splitlines(), delimiter="\t")
        if reader.fieldnames and any(name in ("method", "url", "status") for name in reader.fieldnames):
            return [dict(r) for r in reader]
        fields = ["method", "url", "status", "size", "content_type", "hash", "title", "sensitive_hit", "body_path"]
        rows = []
        for line in text.splitlines():
            parts = line.split("\t")
            rows.append({fields[i]: parts[i] if i < len(parts) else "" for i in range(len(fields))})
        return rows
    return []


def parse_size(value: str) -> int:
    return int(value.split()[0]) if re.match(r"^\d+", value or "") else 0


def split_csv(value: str) -> set[str]:
    return {part.strip() for part in (value or "").split(",") if part.strip()}


def row_blob(row: Dict[str, str]) -> str:
    parts = []
    for key, value in row.items():
        if key in {"body_path", "body", "header_path"} and value and Path(value).exists():
            try:
                parts.append(Path(value).read_text(encoding="utf-8", errors="replace")[:120000])
            except Exception:
                pass
        parts.append(str(value or ""))
    return " ".join(parts)


def score_candidate(status: str, size: int, hits: set[str], decision: str, fp_classes: set[str], blob: str) -> tuple[int, str]:
    if decision in FALSE_POSITIVE_DECISIONS or fp_classes & FALSE_POSITIVE_CLASSES:
        return 0, "Rejected by probe false-positive controls"
    # Only reject 401/403/404 when no strong hits present (stack traces, CORS, PII can appear in error pages)
    if status in {"000"} or size == 0:
        return 0, "Unreachable or empty"
    if status in {"401", "403", "404"} and not (hits & STRONG_HITS):
        return 0, f"{status} without strong impact indicators"
    if NEGATIVE_PATTERNS.search(blob) and not (hits & STRONG_HITS):
        return 5, "Negative/login/error wording without strong impact indicator"

    score = 0
    reasons = []
    if status.startswith("2"):
        score += 20
        reasons.append("2xx response")
    elif status.startswith("3"):
        score += 8
        reasons.append("redirect response")

    weighted_hits = {
        "rce": 70,
        "upload": 55,
        "sql_error": 45,
        "pii": 42,
        "auth": 40,
        "business": 25,
        "cors": 12,  # Base; boosted below if credentials=true
    }
    for hit, weight in weighted_hits.items():
        if hit in hits:
            score += weight
            reasons.append(hit)

    # Boost CORS score when credentials are allowed (exploitable)
    if "cors" in hits and re.search(r'access-control-allow-credentials.*true', blob, re.I):
        score += 25
        reasons.append("cors-credentials=true")

    if decision == "PENDING_REVIEW":
        score += 10
        reasons.append("probe pending review")
    if size >= 200:
        score += 5
        reasons.append("non-trivial body")
    if size >= 3000 and hits & STRONG_HITS:
        score += 10
        reasons.append("large strong-signal body")

    return min(score, 100), ", ".join(reasons) if reasons else "Low signal"


def classify(row: Dict[str, str]) -> Dict[str, str]:
    blob = row_blob(row)
    status = str(row.get("status", ""))
    size = parse_size(str(row.get("size", "0") or "0"))
    hits = {name for name, pat in SENSITIVE_PATTERNS if pat.search(blob)}
    hits.update(split_csv(row.get("sensitive_hit", "")))
    decision_in = row.get("decision", "")
    fp_classes = split_csv(row.get("fp_class", ""))
    score, reason = score_candidate(status, size, hits, decision_in, fp_classes, blob)

    if score >= 75:
        decision = "REPORTABLE_CANDIDATE"
    elif score >= 45:
        decision = "NEED_MORE_EVIDENCE"
    elif score > 0:
        decision = "LOW_SIGNAL"
    else:
        decision = "DO_NOT_SUBMIT"

    return {
        "url": row.get("url", ""),
        "status": status,
        "size": str(size),
        "hits": ",".join(sorted(hits)),
        "score": str(score),
        "decision": decision,
        "reason": reason,
        "fp_class": row.get("fp_class", ""),
        "body_path": row.get("body_path", row.get("body", "")),
        "header_path": row.get("header_path", ""),
    }


def final_verdict(classified: List[Dict[str, str]]) -> tuple[str, str]:
    reportable = [r for r in classified if r["decision"] == "REPORTABLE_CANDIDATE"]
    needs = [r for r in classified if r["decision"] == "NEED_MORE_EVIDENCE"]
    if reportable:
        return "HAS_REPORTABLE_CANDIDATES", "Strong indicators survived false-positive filtering; reproduce manually and collect screenshots before submission."
    if needs:
        return "NEED_MORE_EVIDENCE", "Potential indicators found but impact proof is insufficient; continue with authz/impact validation."
    return "DO_NOT_SUBMIT", "No unauthenticated sensitive data, exploit capability, or high-confidence impact survived the gate."


def main() -> int:
    parser = argparse.ArgumentParser(description="Gate SRC probe results")
    parser.add_argument("probe_results", help="probe_results.tsv path")
    parser.add_argument("--target-profile", default="", help="Optional target_profile.md for duplicate hints")
    parser.add_argument("--out", default="", help="Write final gate markdown")
    parser.add_argument("--json-out", default="", help="Write detailed JSON classification")
    args = parser.parse_args()

    rows = read_rows(Path(args.probe_results))
    classified = [classify(r) for r in rows]
    classified.sort(key=lambda r: int(r["score"]), reverse=True)
    reportable = [r for r in classified if r["decision"] == "REPORTABLE_CANDIDATE"]
    review = [r for r in classified if r["decision"] == "NEED_MORE_EVIDENCE"]
    rejected = [r for r in classified if r["decision"] == "DO_NOT_SUBMIT"]
    low = [r for r in classified if r["decision"] == "LOW_SIGNAL"]
    profile_text = Path(args.target_profile).read_text(encoding="utf-8", errors="replace") if args.target_profile and Path(args.target_profile).exists() else ""
    verdict, reason = final_verdict(classified)

    md = []
    md.append("# SRC Quality Gate\n")
    md.append(f"Verdict: {verdict}\n")
    md.append(f"Reason: {reason}\n")
    md.append(f"Rows analyzed: {len(rows)}\n")
    md.append(f"Reportable candidates: {len(reportable)}\n")
    md.append(f"Need more evidence: {len(review)}\n")
    md.append(f"Low-signal candidates: {len(low)}\n")
    md.append(f"Rejected candidates: {len(rejected)}\n")
    if profile_text:
        md.append("Target profile: loaded\n")
    md.append("\n## Reportable candidates\n")
    if reportable:
        for r in reportable[:30]:
            md.append(f"- score={r['score']} {r['status']} {r['url']} hits={r['hits']} reason={r['reason']} body={r['body_path']}\n")
    else:
        md.append("- none\n")
    md.append("\n## Need more evidence\n")
    if review:
        for r in review[:50]:
            md.append(f"- score={r['score']} {r['status']} {r['url']} hits={r['hits']} reason={r['reason']} body={r['body_path']}\n")
    else:
        md.append("- none\n")
    md.append("\n## Rejected / low signal examples\n")
    for r in [x for x in classified if x["decision"] in {"LOW_SIGNAL", "DO_NOT_SUBMIT"}][:100]:
        md.append(f"- {r['decision']} score={r['score']} {r['status']} {r['url']} fp={r['fp_class']} reason={r['reason']}\n")
    output = "".join(md)

    if args.out:
        Path(args.out).write_text(output, encoding="utf-8")
    if args.json_out:
        Path(args.json_out).write_text(json.dumps(classified, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({
        "verdict": verdict,
        "rows": len(rows),
        "reportable_candidates": len(reportable),
        "review_candidates": len(review),
        "low_signal": len(low),
        "rejected": len(rejected),
        "out": args.out,
        "json_out": args.json_out,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
